version: '3.8'
services:
  backend:
    extends:
      file: backend/docker-compose.backend.yml
      service: backend

  db:
    extends:
      file: database/docker-compose.db.yml
      service: db

networks:
  app_network:
    driver: bridge
