services:
  server:
    extends:
      file: server/docker-compose.server.yml
      service: server

  db:
    extends:
      file: db/docker-compose.db.yml
      service: db

networks:
  app_network:
    driver: bridge
